### PR TITLE
Add angular testing library

### LINKED ISSUE #23: Add Angular's implementation
Hi!

Would it be OK if I submit a PR with an Angular implementation?
You can find the library at [angular-extensions/testing-library](https://github.com/angular-extensions/testing-library).

If it's OK, would it also be OK if I start from the [`cypress`](https://github.com/alexkrolick/testing-library-docs/blob/master/website/pages/en/cypress.js) implementation? Starting from scratch would be a bit difficult since I'm not familiar to write react 😅.

### PR DESCRIPTION
**Pull request by timdeschryver**
This PR adds the Angular wrapper around `dom-testing-library`.
The Angular page is the same as the Cypress page, I just replaced cypress with Angular 😄 .

Closes #23

### CODE REVIEW

**Comment by alexkrolick** [comment]
Do you also want to add this to the home page ecosystem links?

**Comment by timdeschryver** [comment]
Sure! I missed it 😅

**Comment by alexkrolick** [comment]
Great!

**Comment by timdeschryver** [comment]
Thanks 🙏

**Comment by kentcdodds** [comment]
Awesome!

**Pull request merged**
